---
- name: "nxos.cdp: show cdp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: stats
          only_stats: "{{ only_stats }}"
          keys:
          - intf_id
          - platform_id
        - name: set_root_key
          key: neighbors
        - name: set_root_key
          key: cdp
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.cdp: show cdp all"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: stats
          only_stats: "{{ only_stats }}"
          keys:
          - cdp_intf_enabled
          - port_up
        - name: set_root_key
          key: interfaces
        - name: replace_keys
          keys:
          - before: '^cdp_all$'
            after: 'all'
        - name: set_root_key
          key: cdp
        - name: set_root_key
          key: "{{ fact_key }}"
