---
- name: "nxos.spanning_tree: show spanning-tree blockedports"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show spanning-tree blockedports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - spanning-tree
          - blockedports
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: blockedports
        - name: set_root_key
          key: spanning_tree
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.spanning_tree: show spanning-tree inconsistentports"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show spanning-tree inconsistentports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - spanning-tree
          - inconsistentports
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: inconsistentports
        - name: set_root_key
          key: spanning_tree
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.spanning_tree: show spanning-tree active detail"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show spanning-tree spanning-tree active detail"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - spanning-tree
          - active
          - detail
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: detail
        - name: set_root_key
          key: active
        - name: set_root_key
          key: spanning_tree
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.spanning_tree: show spanning-tree root detail"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show spanning-tree spanning-tree root detail"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - spanning-tree
          - root
          - detail
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: detail
        - name: set_root_key
          key: root
        - name: set_root_key
          key: spanning_tree
        - name: set_root_key
          key: "{{ fact_key }}"

